import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationMenu from "@/app/component/Menu";
import Footer from "@/app/component/Footer";

const interFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // optional
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head />
      <body className={`${interFont.variable} antialiased`}>
        <header className="sticky top-0 z-50 bg-white shadow-md">
          <NavigationMenu />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
