import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const NavigationMenu = dynamic(() => import("@/app/component/Menu"), { ssr: false });
const Footer = dynamic(() => import("@/app/component/Footer"), { ssr: false });

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${interFont.variable} antialiased`} suppressHydrationWarning>
        <header className="sticky top-0 z-50 bg-white shadow-md">
          <NavigationMenu />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
