import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter font
import "./globals.css";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add any meta tags, title, or links here */}
      </head>
      <body className={`${interFont.variable} antialiased`}>
        <header>
          {/* Add header content here */}
        </header>
        {children}
        <footer>
          {/* Add footer content here */}
        </footer>
      </body>
    </html>
  );
}